url: "https://PBI-DataVizzle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/my-datavizzle-blog-github-io" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
